// <auto-generated />
using System;
using Aria.Web.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aria.Web.Migrations.InitialCreate
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617114036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Aria.Web.Data.Agents.AgentCronJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CogitationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubAgentId");

                    b.HasIndex("UserId");

                    b.ToTable("AgentCronJobs");
                });

            modelBuilder.Entity("Aria.Web.Data.Cogitations.Cogitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AriaAvatarKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubAgentId");

                    b.HasIndex("UserId");

                    b.ToTable("Cogitations");
                });

            modelBuilder.Entity("Aria.Web.Data.Cogitations.CogitationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CogitationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThinkingContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CogitationId");

                    b.ToTable("CogitationMessages");
                });

            modelBuilder.Entity("Aria.Web.Data.Llm.ModelFormatCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThinkingFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointUrl", "ModelId")
                        .IsUnique();

                    b.ToTable("ModelFormatCaches");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchetypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarSpriteKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledMcpNamesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedPersonality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelSourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDirectives")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SubAgents");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgentSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubAgentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("SubAgentId", "SkillId")
                        .IsUnique();

                    b.ToTable("SubAgentSkills");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgentToolState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubAgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubAgentId", "ToolId")
                        .IsUnique();

                    b.ToTable("SubAgentToolStates");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarSpriteKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModelSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserLlmApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyB64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProviderName")
                        .IsUnique();

                    b.ToTable("UserLlmApiKeys");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserMcpServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMcpServers");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserOAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserOAuthTokens");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserSourcePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SourceName")
                        .IsUnique();

                    b.ToTable("UserSourcePreferences");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserToolConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ToolId")
                        .IsUnique();

                    b.ToTable("UserToolConfigs");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserVoxSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixingChannelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionChannelName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserVoxSettings");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltTurn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("WargameBuildings");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameFaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompactedContext")
                        .HasColumnType("TEXT");

                    b.Property<int>("Food")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wood")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WargameFactions");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WargameMaps");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerFactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("OwnerFactionId");

                    b.ToTable("WargameTiles");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameTurnLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("WargameTurnLogs");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("WargameUnits");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.AgentCronJob", b =>
                {
                    b.HasOne("Aria.Web.Data.Agents.SubAgent", "SubAgent")
                        .WithMany()
                        .HasForeignKey("SubAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubAgent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Cogitations.Cogitation", b =>
                {
                    b.HasOne("Aria.Web.Data.Agents.SubAgent", "SubAgent")
                        .WithMany()
                        .HasForeignKey("SubAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubAgent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Cogitations.CogitationMessage", b =>
                {
                    b.HasOne("Aria.Web.Data.Cogitations.Cogitation", "Cogitation")
                        .WithMany("Messages")
                        .HasForeignKey("CogitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cogitation");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.Skill", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgent", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgentSkill", b =>
                {
                    b.HasOne("Aria.Web.Data.Agents.Skill", "Skill")
                        .WithMany("SubAgentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aria.Web.Data.Agents.SubAgent", "SubAgent")
                        .WithMany("SubAgentSkills")
                        .HasForeignKey("SubAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("SubAgent");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgentToolState", b =>
                {
                    b.HasOne("Aria.Web.Data.Agents.SubAgent", "SubAgent")
                        .WithMany("ToolStates")
                        .HasForeignKey("SubAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubAgent");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserLlmApiKey", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserMcpServer", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserSourcePreference", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Users.UserToolConfig", b =>
                {
                    b.HasOne("Aria.Web.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameBuilding", b =>
                {
                    b.HasOne("Aria.Web.Data.Wargame.WargameFaction", "Faction")
                        .WithMany("Buildings")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameTile", b =>
                {
                    b.HasOne("Aria.Web.Data.Wargame.WargameMap", "Map")
                        .WithMany("Tiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aria.Web.Data.Wargame.WargameFaction", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerFactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Map");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameTurnLog", b =>
                {
                    b.HasOne("Aria.Web.Data.Wargame.WargameFaction", "Faction")
                        .WithMany("TurnLogs")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameUnit", b =>
                {
                    b.HasOne("Aria.Web.Data.Wargame.WargameFaction", "Faction")
                        .WithMany("Units")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("Aria.Web.Data.Cogitations.Cogitation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.Skill", b =>
                {
                    b.Navigation("SubAgentSkills");
                });

            modelBuilder.Entity("Aria.Web.Data.Agents.SubAgent", b =>
                {
                    b.Navigation("SubAgentSkills");

                    b.Navigation("ToolStates");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameFaction", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("TurnLogs");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Aria.Web.Data.Wargame.WargameMap", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
