<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aria.Agent\Aria.Agent.csproj" />
    <ProjectReference Include="..\Aria.Tools\Aria.Tools.csproj" />
    <ProjectReference Include="..\Aria.Shared\Aria.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
